id: P001715
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN412
  title: ཞྭ་དམར་དྲུག་པ་ཆོས་ཀྱི་དབང་ཕྱུག་གི་རྟོགས་པ་བརྗོད་པ།
  author: ''
  volumes:
    9e9d40a4f5ba4ef8b895f1ddc56e8ce0:
      image_group_id: I3CN2853
      title: ''
      volume_number: 1
      total_pages: 378
