id: ID7F2D2DA
legacy_id: P001715
ocr_import_info:
  bdrc_scan_id: W3CN412
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T10:49:24'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T14:22:50.155157+00:00'
last_modified: 2022-09-03 22:23:01.002396
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN412
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN412
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཞྭ་དམར་དྲུག་པ་ཆོས་ཀྱི་དབང་ཕྱུག་གི་རྟོགས་པ་བརྗོད་པ།
  author: ཀརྨ་པ ༡༠་ཆོས་དབྱིངས་རྡོ་རྗེ།
statistics:
  ocr_word_mean_confidence_index: 0.7089689925209671
  ocr_word_median_confidence_index: 0.7799999713897705
quality: null
bases:
  I3CN2853:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN2853
      total_pages: 378
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN2853.txt
    statistics:
      ocr_word_median_confidence_index: 0.7799999713897705
      ocr_word_mean_confidence_index: 0.7089689925209671
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
